# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Angela Brisotto, Dott.ssa | Tilia Translations
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Mi chiamo Angela Brisotto e costruisco ponti che mettono in contatto l’inglese e il polacco all’italiano. Uso analisi, accuratezza e l’arte della parola per tradurre testi, localizzare siti web, revisionare traduzioni, correggere testi e trascrivere tracce audio e video. Aiuto chi è cresciuto in Italia a sgranchire il proprio inglese. Benvenut* sul mio sito!

copyright: 'TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
P.IVA: 05247030264
<br>
31027, Spresiano (TV)
<br>
Italia
<br>
<br>
Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.
<br>
<br>'

credits: 'Nota sulle email: 
<br>
<br>
Rispondo esclusivamente a email contenenti domande sui miei servizi, richieste di acquisto di una o più lezioni e richieste di preventivo.
<br>
Quando risponderò alla tua email? Dal lunedì al giovedì dalle 9.00 alle 16.00 (ora italiana).
<br>
Grazie per l’attenzione. &#127861;
<br>
<br>
Indirizzo: <a href="mailto:angela@tiliatranslations.it">angela@tiliatranslations.it</a>
<br>
Destinataria: Angela Brisotto (lei/di lei)'



# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
