# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.tiliatranslations.it
title: Tilia Translations
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Angela Brisotto, linguista, insegna inglese, traduce testi dall’inglese e dal polacco all’italiano, revisiona testi e trascrive registrazioni.

copyright: |
  TILIA TRANSLATIONS DI ANGELA BRISOTTO
  <br>
  P.IVA: 05247030264
  <br>
  31027, Spresiano (TV)
  <br>
  Italia
  <br>
  <br>
  Copyright &copy; 2022 Tilia Translations di Angela Brisotto. All Rights Reserved.
  Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.
  <br>
  <br>

credits: |
  COME CONTATTARMI 
  <br>
  <br>
  Se vuoi contattarmi per valutare la possibilità di lavorare insieme, scrivimi un’email con tutti i dettagli della tua richiesta. Risponderò al tuo messaggio entro 24 ore durante il mio orario d’ufficio, ovvero dal lunedì al giovedì dalle 9.00 alle 16.00 (ora italiana). 
  <br>
  <br>
  Manda <a href="mailto:angela@tiliatranslations.it">un’email</a> a Angela Brisotto: angela@tiliatranslations.it



# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: youtube
    url: https://www.youtube.com/channel/UCd56fXkhghdBQIMN6frP6lA
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
